import Head from "next/head";
import { Press_Start_2P } from "next/font/google";
import styles from "@src/styles/Home.module.css";
import { GameWrapper } from "@components/pages/GameWrapper";

const pressStart2p = Press_Start_2P({
    weight: "400",
    subsets: ["latin"],
});

export default function Home() {
    return (
        <>
            <Head>
                <title>Whack a Mole</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={`${styles.main} ${pressStart2p.className}`}>
                <GameWrapper />
            </main>
        </>
    );
}

